VIDEO_CAPTURE_DEVICE = '/dev/video0'
VIDEO_CAPTURE_FRAME_SHAPE = (640, 480)
VIDEO_CAPTURE_FORMAT = 'NV12'  # 'YUY2'
VIDEO_CAPTURE_FRAMERATE = 30

VIDEO_LOG_FRAME_SHAPE = VIDEO_CAPTURE_FRAME_SHAPE
VIDEO_LOG_FRAMERATE = VIDEO_CAPTURE_FRAMERATE

ORB_DETECTOR_MAX_FEATURES = 200

IMU_SERIAL_DEVICE = '/dev/ttyACM0'
IMU_OUT_DATA_RATE = 100

MAX_QUEUE_LEN = 100

FPS_MAX_COUNTER = 120

LOGGER_DURATION = 10  # seconds
